name: Build, Test, Release, Deploy

on:
  push:
    branches:
      - main

jobs:
  build-test-release:
    name: Build, Test, Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mlc-llm:latest

      - name: Run Unit Tests
        run: |
          docker run --rm ghcr.io/${{ github.repository_owner }}/mlc-llm:latest ./scripts/test-image.sh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: mlc-llm-v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          draft: false
          prerelease: false

  deploy:
    name: Deploy to Fly.io
    needs: build-test-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only --image ghcr.io/${{ github.repository_owner }}/mlc-llm:latest
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
